# Generated by Django 5.0.2 on 2024-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracoapp', '0004_products_payment_payment_method_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='TXN123456789', max_length=255),
        ),
    ]
